### ISSUE TITLE
Vikram TODO

### ISSUE THREAD

**Issue by vikramc1** [neurodata/ndmg#108]
- [ ] Identify a quantitative measure to assess accuracy of registration (unaligned head < aligned head and unaligned white matter < perfect white matter)
- [ ] Pseudocode for algorithm assessing accuracy.
- [ ] Testing algorithm on known data (to determine if coded properly)
- [ ] Testing algorithm on FLIRT registration with a few sample brains
- [ ] Testing algorithm on FNIRT
- [ ] Testing algorithm after FSL FAST + FLIRT BBR 
- [ ] Testing algorithm after FSL FAST + FNIRT BBR

**Comment by vikramc1** [comment]
possible quantitative measures:
1) white matter overlap (binary brain)
2) gray matter overlap (binary brain)
3) Mean squared error

**Comment by vikramc1** [comment]
1) FLIRT pseudocode (flowchart)
2) explain quantitative evaluation in words

**Comment by gkiar** [comment]
OBE :)
