### ISSUE TITLE
TODO for version v1.0.0

### ISSUE THREAD

**Issue by Lawreros** [neurodata/ndmg#406]
- [x] Update README
- [x] Add ability to run both diffusion and functional pipelines at the same time
- [x] Check/have QA figures generated for each major step described in m2g paper
- [x] Finalize output folder structure (consistent as possible across diffusion and functional pipeline)
- [x] Convert existing aws repositories into output folder structure
- [x] Check that all docstrings are accurate
- [ ] Update pytest with example 4mm resolution diffusion and functional scans (to account for travis' limited memory)
- [ ] Add discriminability and connection functionality into m2g utils
- [] Create Docker image for dwi-only, func-only, and both (image size varies a lot)
- [ ] Go through m2g issues
- [x] Update downloads on the neurodata website
- [ ] make updated version of this: https://zenodo.org/record/1161284
